spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdb:mysql://127.0.0.1:3306/downpu
   username: "root"
   password: "0000"
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
  thymeleaf:
  prefix: /resources/static
server:
  port: 8081

